groups:
  - name: verify
    jobs:
      - check

__github_access_token: &github_access_token
  access_token: ((github-access-token))


resource_types:
  - name: pull-request-resource
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.21.0 # see https://github.com/telia-oss/github-pr-resource/issues/233
  - name: github-status
    type: docker-image
    source:
      repository: "dpb587/github-status-resource"
      tag: "master"
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: master-branch
    type: git
    icon: source-branch
    source:
      branch: master
      private_key: ((private_key_coin_definitions))
      uri: git@github.com:blockchain/coin_definitions.git

  - name: pull-request
    type: pull-request-resource
    icon: source-branch
    check_every: 1m
    source:
      repository: blockchain/coin_definitions
      <<: *github_access_token

  - name: commit-status
    type: github-status
    icon: github
    source:
      repository: blockchain/service-nabu-core
      <<: *github_access_token
      context: ci/master
  - name: pr-dev-label
    type: pull-request-resource
    check_every: 1m
    icon: source-branch
    source:
      repository: blockchain/service-nabu-core
      labels:
        - build-dev-image
      <<: *github_access_token

  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack_hook))

jobs:
  - name: check
    plan:
      - in_parallel:
          - do:
              - get: pull-request
                trigger: true
                version: every
              - put: update-pr-status
                resource: pull-request
                params:
                  path: pull-request
                  context: check
                  status: pending
      - task: check
        image: jre-image
        config:
          platform: linux
          outputs:
            - name: comment
          run:
            path: /bin/bash
            args:
              - -c
              - |
                #!/bin/bash
                export TERM=dumb
                set -e

                cd pull-request

                mkdir -p output

                echo "## Coin Definition Check Result" >> comment/txt

                echo $(./check.sh) >> comment/txt

        on_failure:
          put: pull-request
          params:
            path: pull-request
            context: test
            status: failure

      - in_parallel:
        - put: pull-request
          params:
            path: pull-request
            comment_file: comment/txt
            context: test
            status: success
